name: receipt_vault
description: Forever Receipt Vault - Mobile app for receipt storage and management
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # Camera & Image Processing
  camera: ^0.10.5+2
  image_picker: ^1.0.1
  image_cropper: ^5.0.1
  image: ^4.0.17
  
  # Authentication & Security
  local_auth: ^2.1.6
  crypto: ^3.0.3
  
  # Network & Storage
  dio: ^5.2.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  
  # Connectivity & Offline Support
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  
  # ML & OCR
  google_ml_kit: ^0.15.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  permission_handler: ^10.4.3
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  
  # PDF & File Handling
  pdf: ^3.10.4
  path: ^1.8.3
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code Generation
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700