name: receipt_vault
description: Forever Receipt Vault - Mobile app for receipt storage and management
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0
  settings_ui: ^2.0.2
  
  # Camera & Image Processing
  camera: ^0.10.5+2
  image_picker: ^1.0.1
  image_cropper: ^5.0.1
  image: ^4.0.17
  
  # Authentication & Security
  local_auth: ^2.1.6
  local_auth_android: ^1.0.34
  local_auth_ios: ^1.0.16
  crypto: ^3.0.3
  
  # WorkOS Authentication
  webview_flutter: ^4.2.2
  flutter_secure_storage: ^9.0.0
  
  # Routing
  go_router: ^13.0.0
  
  # Network & Storage
  dio: ^5.2.1+1
  http: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  
  # Connectivity & Offline Support
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  
  # ML & OCR
  google_ml_kit: ^0.15.0
  speech_to_text: ^6.3.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  permission_handler: ^10.4.3
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
  device_info_plus: ^9.1.0
  
  # PDF & File Handling
  pdf: ^3.10.4
  path: ^1.8.3
  file_picker: ^5.3.2
  
  # Required for serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  
  # Animation & UI Enhancements
  lottie: ^2.6.0
  animated_text_kit: ^4.2.2
  
  # Additional utilities
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Testing
  mockito: ^5.4.2
  shared_preferences: ^2.2.0
  
  # Code Generation
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/