version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: receipt_vault_db
    environment:
      POSTGRES_DB: receipt_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - receipt_vault

  redis:
    image: redis:7-alpine
    container_name: receipt_vault_redis
    ports:
      - "6379:6379"
    networks:
      - receipt_vault

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: receipt_vault_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - receipt_vault

  qdrant:
    image: qdrant/qdrant:latest
    container_name: receipt_vault_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - receipt_vault

  minio:
    image: minio/minio:latest
    container_name: receipt_vault_storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - receipt_vault

volumes:
  postgres_data:
  es_data:
  qdrant_data:
  minio_data:

networks:
  receipt_vault:
    driver: bridge